repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      additional_dependencies: [".[jupyter]"]
      language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        # Ignore all format-related checks as Black takes care of those.
        args: ["--ignore", "E203,E501,W503,F403", "--select", "E,W,F", '--per-file-ignores=__init__.py:F401,F405,E402', '--exclude','tests/*']