version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx docs/"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  builder: html
  fail_on_warning: false