version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
      pre_create_environment:
         - asdf plugin add uv
         - asdf install uv latest
         - asdf global uv latest
      create_environment:
         - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
      install:
         - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --extra docs
      pre_build:
        # Generate the Sphinx configuration for this Jupyter Book so it builds.
        - "jupyter-book config sphinx docs/"
        - "python ./stimupy/_docs/generate_stimulus_images.py"


sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false