#!/bin/bash
set -e  # don't allow errors to fail silently
echo `which pip`  # in case the wrong `pip` is used, this will let us debug

# Install and enable extensions...
pip install "jupytext[myst]>=1.13.3"
jupyter nbextension install --py jupytext --user
jupyter nbextension enable --py jupytext --user
jupyter lab build
jupyter serverextension enable jupytext

# Install stimupy
pip install -e .
