# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: stimupy
author: Lynn Schmittwilken, Marianne Maertens, Joris Vincent
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: stimupy.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/computational-psychology/stimupy  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  #branch: dev_docs  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"

sphinx:
  extra_extensions:
    - sphinx.ext.intersphinx
    - autoapi.extension             # generate API documentation of functions in modules
    - sphinx.ext.napoleon           # recognize NumPy style docstrings
    - sphinx.ext.viewcode           # add links to source code in API reference
    - hoverxref.extension

  config:
    templates_path: ['_templates']  # Path(s) that contain templates, relative to this config
    exclude_patterns: ['_build', '_templates']
    suppress_warnings: ["etoc.toctree"]

    # Auto documentation (autoapi, autodoc)
    autoapi_dirs: ['../stimupy']
    autoapi_root: 'reference/'
    autoapi_add_toctree_entry: False
    autoapi_keep_files: True

    autoapi_own_page_level: 'function'
    autodoc_typehints: "signature"
    autoapi_options: [
        "members",
        "undoc-members",
        "show-module-summary",
    ]

    autodoc_default_options: {
     "members": True,                # Include module/class members.
     "member-order": 'bysource',     # Order members as in source file.
    }

    # Intersphinx
    intersphinx_mapping:
        python:
          - 'https://docs.python.org/3/'
          - null
        numpy [stable]:
          - 'https://numpy.org/doc/stable/'
          - null
        matplotlib [stable]:
          - 'https://matplotlib.org/stable/'
          - null
        pandas [latest?]:
          - 'https://pandas.pydata.org/docs/'
          - null
        scipy [latest]:
          - 'https://docs.scipy.org/doc/scipy/'
          - null
        pillow [latest]:
          - 'https://pillow.readthedocs.io/en/latest/'
          - null

    # Hoverxref Extension
    hoverxref_auto_ref: True
    hoverxref_intersphinx: [
        "python",
        "numpy",
        "matplotlib",
        "scipy",
    ]
    hoverxref_domains: ["py", "numpy", "matplotlib", "scipy"]
    hoverxref_role_types: {
        "hoverxref": "modal",
        "ref": "modal",  # for hoverxref_auto_ref config
        "mod": "tooltip",
        "class": "tooltip",
        "func": "tooltip",
        "obj": "tooltip"
    }