# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: stimupy
author: Lynn Schmittwilken, Marianne Maertens, Joris Vincent
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: stimupy.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/computational-psychology/stimupy  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: dev_docs  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"

sphinx:
  extra_extensions:
    - sphinx.ext.intersphinx
    - sphinx.ext.autosummary        # generate summary tables of functions in modules
    - sphinx.ext.napoleon           # recognize NumPy style docstrings

  config:
    autosummary_generate: True  # Actually use sphinx.ext.autosummary
    add_module_names: False         # Don't include module names in autosummary tables
    intersphinx_mapping:
        numpy [stable]:
          - 'https://numpy.org/doc/stable/'
          - null
        matplotlib [stable]:
          - 'https://matplotlib.org/stable/'
          - null
        pandas [latest?]:
          - 'https://pandas.pydata.org/docs/'
          - null
        scipy [latest]:
          - 'https://docs.scipy.org/doc/scipy/'
          - null
        pillow [latest]:
          - 'https://pillow.readthedocs.io/en/latest/'
          - null
    suppress_warnings: ["etoc.toctree"]