name: Linting, Formatting

on:
  push:
    branches: [ main, dev, build ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # Checkout the stimupy repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Lint using Ruff
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check --ignore F403,F405"