name: Test

on: push

jobs:
  test:
    name: PY ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.11']
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install nox
        run: pip install nox
      - name: Install (testing) requirements
        run: pip install -r requirements.txt
      - name: Install stimupy to be tested
        run: pip install .
      - name: Run tests for $ {{ matrix.python_version }} through nox
        run: nox --non-interactive --error-on-missing-interpreter --session "tests-${{ matrix.python_version }}" -- --full-trace
