name: Test

on: 
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: ${{ matrix.os}} / py${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, macOS]
        python_version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install (testing) requirements
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt
      - name: Install stimupy to be tested
        run: |
          pip install .
      - name: Run tests for ${{ matrix.python_version }} through nox
        run: |
          pipx run nox --non-interactive --error-on-missing-interpreter --session "tests-${{ matrix.python_version }}"
