name: Bump version (if necessary)

on:
  pull_request_target:
    types:
      - closed
  workflow_dispatch:

jobs:
  bump-version:
    if: (github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # checkout full commit history
          token: ${{ secrets.GHA_Token }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Configure git to be able to push to repo
        env:
          GH_TOKEN: ${{ secrets.GHA_Token }}
        run: |
          git config user.name token
          git config user.email token@github.com

      - name: Bump version, build & upload release assets using Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GHA_Token }}
        run: |
          pipx run python-semantic-release publish -v DEBUG